name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install frontend dependencies
      run: |
        cd client
        npm ci
        
    - name: Install backend dependencies
      run: |
        cd server
        npm ci
        
    - name: Run frontend tests
      run: |
        cd client
        npm test
        
    - name: Run backend tests
      run: |
        cd server
        npm test